[versions]
kotlin = "2.1.21"
junit = "4.13.2"
androidxTestJunit = "1.2.1"
espresso = "3.6.1"
material = "1.12.0"
swiperefreshlayout = "1.1.0"
appcompat = "1.7.0"
coreKtx = "1.16.0"
constraintlayout = "2.2.1"
recyclerview = "1.4.0"
appUpdateKtx = "2.1.0"
reviewKtx = "2.0.2"
preferenceKtx = "1.2.1"
databindingCompiler = "3.6.1"
retrofit = "2.11.0"
room = "2.7.1"
lifecycle = "2.9.0"
lifecycleExtensions = "2.2.0"
firebaseMessaging = "24.1.1"
firebaseConfigKtx = "22.1.2"
firebaseAnalyticsKtx = "22.4.0"
firebaseCrashlyticsKtx = "19.4.3"
pagingRuntimeKtx = "3.3.6"
facebookAudienceNetworkSdk = "6.20.0"
autostarter = "1.1.0"
lottie = "6.5.2"
browser = "1.8.0"
webkit = "1.13.0"
hilt = "2.56.2"
hiltNavigation = "1.2.0"
hiltWork = "1.2.0"  # Add Hilt Work version
glide = "4.16.0"
glideCompiler = "4.16.0"
billingKtx = "7.1.1"
okhttpLoggingInterceptor = "4.12.0"
timber = "5.0.1"
composeBom = "2025.05.01"
activityCompose = "1.10.1"
accompanist = "0.36.0"
workRuntimeKtx = "2.10.1"
playServicesAds = "23.0.0"

gradlePlugin = "8.13.1"
googleServices = "4.4.2"
firebaseCrashlytics = "3.0.3"
ksp = "2.1.21-2.0.1"

okhttp = "4.12.0"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

junit = { module = "junit:junit", version.ref = "junit" }
androidxTestJunit = { module = "androidx.test.ext:junit", version.ref = "androidxTestJunit" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

material = { module = "com.google.android.material:material", version.ref = "material" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }

appUpdateKtx = { module = "com.google.android.play:app-update-ktx", version.ref = "appUpdateKtx" }
reviewKtx = { module = "com.google.android.play:review-ktx", version.ref = "reviewKtx" }

preferenceKtx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }

databindingCompiler = { module = "com.android.databinding:compiler", version.ref = "databindingCompiler" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitGson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofitScalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }

roomRuntime = { module = "androidx.room:room-runtime", version.ref = "room" }
roomKtx = { module = "androidx.room:room-ktx", version.ref = "room" }
roomPaging = { module = "androidx.room:room-paging", version.ref = "room" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }

viewmodelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
livedataKtx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycleExtensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }

firebaseMessaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
firebaseConfigKtx = { module = "com.google.firebase:firebase-config-ktx", version.ref = "firebaseConfigKtx" }
firebaseAnalyticsKtx = { module = "com.google.firebase:firebase-analytics-ktx", version.ref = "firebaseAnalyticsKtx" }
firebaseCrashlyticsKtx = { module = "com.google.firebase:firebase-crashlytics-ktx", version.ref = "firebaseCrashlyticsKtx" }

pagingRuntimeKtx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingRuntimeKtx" }

facebookAudienceNetworkSdk = { module = "com.facebook.android:audience-network-sdk", version.ref = "facebookAudienceNetworkSdk" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
autostarter = { module = "com.github.judemanutd:autostarter", version.ref = "autostarter" }

lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
lottieCompose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }

browser = { module = "androidx.browser:browser", version.ref = "browser" }
webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }

hiltAndroid = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hiltCompiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hiltNavigationFragment = { module = "androidx.hilt:hilt-navigation-fragment", version.ref = "hiltNavigation" }
hiltWork = { module = "androidx.hilt:hilt-work", version.ref = "hiltWork" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glideCompiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glideCompiler" }

billingKtx = { module = "com.android.billingclient:billing-ktx", version.ref = "billingKtx" }

okhttpLoggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttpLoggingInterceptor" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

composeBom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
composeUi = { module = "androidx.compose.ui:ui" }
composeMaterial = { module = "androidx.compose.material:material" }
composeMaterial3 = { module = "androidx.compose.material3:material3" }
composeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
composeUiTooling = { module = "androidx.compose.ui:ui-tooling" }

accompanistThemeAdapter = { module = "com.google.accompanist:accompanist-themeadapter-appcompat", version.ref = "accompanist" }

workRuntimeKtx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }

leakCanary = { module = "com.squareup.leakcanary:leakcanary-android", version = "2.14" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

[plugins]
application = { id = "com.android.application", version.ref = "gradlePlugin" }
library = { id = "com.android.library", version.ref = "gradlePlugin" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebaseCrashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
org-jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }